version: v2
modules:
  - path: slg-proto
deps: []
lint:
  use:
    - STANDARD
  except:
    - FIELD_LOWER_SNAKE_CASE
    - ENUM_VALUE_PREFIX
    - ENUM_ZERO_VALUE_SUFFIX
  ignore:
    - slg-proto/*/deprecated/**
    - slg-proto/*/experimental/**
breaking:
  use:
    - FILE
  ignore:
    - slg-proto/*/experimental/**